`r builder$heading(1)` JMeter Charts

`r builder$heading(2)` Common

```{r echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

.suc <- current_data[success == TRUE]

.r <- top(
    .suc, 
    list(top_avg = mean, top_rps = length), 
    "elapsed", 
    "label"
)
```

`r builder$heading(3)` Running Users

```{r results='asis', message=FALSE, echo=FALSE, warning=FALSE}
builder$include("jmeter/charts/running_users", arguments = list(
    chart_data = current_data
))
```

`r builder$heading(3)` Top `r param_top_els` Transactions

```{r results='asis', message=FALSE, echo=FALSE, warning=FALSE}
builder$include("jmeter/charts/response_time", arguments = list(
    chart_data = .suc[label %in% .r$top_avg],
    chart_prefix = "Top successful",
    chart_by = "label",
    chart_total_layer = FALSE,
    chart_mode_latency = FALSE
))
```

```{r results='asis', message=FALSE, echo=FALSE, warning=FALSE}
builder$include("jmeter/charts/transactions_per_sec", arguments = list(
    chart_data = .suc[label %in% .r$top_rps],
    chart_prefix = "Top successful",
    chart_by = "label",
    chart_total_layer = FALSE
))
```
