```{r echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

#' Fragment that describes JMeter test summary table for regular report.
#' 
#' @param table_data data for table.
#' @param table_slas SLA results storage object.
#' @param table_history historical data storage object.
#' @param table_metric_descr table metric description object (part of jmeter schema).
#' @param table_mode indicates table aggregation mode, 
#' one of "total", "group", "transaction".
#' @param table_dump_location path where table data should be saved
#' @param table_dump_append do not drop table_dump_location if it exists
```

`r builder$heading(1)` `r capitalize(table_mode)` `r table_metric_descr$name_full`

```{r results='asis', echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

table_history_excludes <- NULL
table_history_name <- "name"

if (table_mode == "total") {
    table_group_key <- NULL
    table_suppress <- "group"
} else if (table_mode == "group") {
    table_group_key <- "businessGroup"
    table_history_excludes <- "name"
    table_history_name <- "Total"
    table_suppress <- "group"
} else {# transaction
    table_group_key <- "label"
    table_suppress <- NULL
}

table_printer_plugins <- list(
    history = list(
        ptable_history_obj = table_history,
        ptable_history_loc = c(
            table_metric_descr$name_hist,
            "group",
            table_history_name
        ),
        ptable_history_excludes = table_history_excludes
    )
)

if (!is.null(table_dump_location)) {
    table_printer_plugins$dumper <- list(
        ptable_dumper_where = table_dump_location,
        ptable_dumper_append = table_dump_append
    )
}

builder$include("common/tables/generic_summary", arguments = list(
    summary_table = distribution_summary(
        table_data,
        group_key = table_group_key,
        stat_col = table_metric_descr$name_sys,
        success_only = param_stat_success
    ),
    summary_class = paste0(table_metric_descr$name_sys, ".summary"),
    summary_subclass = table_mode,
    summary_bgroup = "group",
    summary_slas = table_slas,
    summary_plugins = table_printer_plugins,
    summary_suppress = table_suppress,
    summary_orderby = "avg",
    summary_orderby_desc = TRUE,
    summary_unit = table_metric_descr$units
))
```
